save

diff --git a/.buildkite/hooks/pre-command b/.buildkite/hooks/pre-command
--- a/.buildkite/hooks/pre-command
+++ b/.buildkite/hooks/pre-command
@@ -2,86 +2,58 @@
 
 set -eo pipefail
 
-if [ "$DOCKER_CLEAN_BEFORE" == "true" ]; then
-  ./dishctl.sh clean_docker_if_disk_full
-fi
-
+# env first
 # ensure data dir for caches
 mkdir -p /data
 mkdir -p $HOME/data
 PWD=$(pwd)
-export GOOGLE_APPLICATION_CREDENTIALS="$PWD/k8s/etc/dish-gcloud.enc.json"
 export PATH=$PATH:$HOME/bin
-export PATH=$PATH:"$HOME/bin/google-cloud-sdk/bin"
-export LD_LIBRARY_PATH="/usr/local/lib"
+export FLYCTL_INSTALL="/root/.fly"
+export PATH="$FLYCTL_INSTALL/bin:$PATH"
 
-mkdir -p $HOME/bin
-
-function init_gcloud() {
-  echo $(date -u) "gcloud init..."
-  ./dishctl.sh gcloud_init
-}
-
+# install second
+# bail early on fail
 if [ "$FIRST_STEP" == "true" ]; then
   echo $(date -u) "git-crypt..."
   echo "$GPG_KEY" > key
   gpg --import key > gpg-import.log
   git-crypt unlock > gpg-crypt.log
-
-
-  if (which gcloud > /dev/null); then
-    init_gcloud
-  else
-    apt-get install -y libssl-dev libffi-dev
-    ./dishctl.sh install_gcloud_sdk
-    gcloud config set component_manager/disable_update_check true
-  fi
-
-fi
-
-# bail early on fail
-if [ "$FIRST_STEP" == "true" ]; then
-  rm -f /opt/ci/inner/skip || true
+  rm -f exit_this_build || true
 else
-  if [[ -f "/opt/ci/inner/skip" ]]; then
-      SKIP_STEPS=$(cat /opt/ci/inner/skip)
+  if [[ -f "exit_this_build" ]]; then
+      SKIP_STEPS=$(cat exit_this_build)
       export SKIP_STEPS
       echo SKIP_STEPS: "$SKIP_STEPS"
       exit 1
   fi
 fi
 
-if (which netstat > /dev/null); then
-  echo $(date -u) "netstat installed"
-else
+if [ ! -f $(which netstat) ]; then
   apt-get update && apt-get install -y net-tools
-  echo $(date -u) "netstat installed"
 fi
+echo $(date -u) "netstat installed"
 
-if (which psql > /dev/null); then
-  echo $(date -u) "psql installed"
-else
+if [ ! -f $(which flyctl) ]; then
+  curl -L https://fly.io/install.sh | sh
+fi
+echo $(date -u) "flyctl installed"
+
+if [ ! -f $(which psql) ]; then
   apt-get update && apt-get install -y postgresql-client
-  echo $(date -u) "psql installed"
 fi
+echo $(date -u) "psql installed"
 
-if (which node > /dev/null); then
-  echo $(date -u) "node installed"
-else
+if [ ! -f $(which node) ]; then
   apt-get update && apt-get install -y nodejs
-  echo $(date -u) "node installed"
 fi
+echo $(date -u) "node installed"
 
-if (which npm > /dev/null); then
-  echo $(date -u) "npm installed"
-else
+if [ ! -f $(which npm) ]; then
   apt-get update && apt-get install -y npm
-  echo $(date -u) "npm installed"
 fi
+echo $(date -u) "npm installed"
 
-if (which docker > /dev/null); then
-  echo $(date -u) "node/docker/npm installed"
-else
+if [ ! -f $(which docker) ]; then
   apt-get update
   apt-get install -y docker docker-compose nodejs npm
   curl -o- -L https://yarnpkg.com/install.sh | bash
@@ -91,6 +63,13 @@ fi
 if [ ! -f /usr/local/bin/hasura ]; then
   curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
 fi
+
+if [ "$DOCKER_CLEAN_BEFORE" == "true" ]; then
+  ./dishctl.sh clean_docker_if_disk_full
+fi
+
+
+mkdir -p $HOME/bin
 
 ./dishctl.sh dish_docker_login
 echo $(date -u) "docker logged in"
